### ISSUE TITLE
wholeProfile file for Arabidopsis Thaliana

### ISSUE THREAD

**Issue by akshaysuhag1996** [YulongNiu/PhyloProfileWeb#1]
Hello @YulongNiu 

I am Akshay, a student of M.Sc in Bioinformatics. I was looking for the phylogenetic profile of Arabidopsis genes but unfortunately, I am unable to do so.

Kindly provide me the path for the phylogenetic profile of Arabidopsis genes, if possible.

I will highly appreciate your help and support.

Thank you,
Best regards
Akshay

**Comment by YulongNiu** [comment]
@akshaysuhag1996 I have sent you the Arabidopsis files by email.
